//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /Zi /Od /Gfp /E OCC_PS /Fo
//    \\?\C:\Projects\Vektoria_2015-06-03\Vektoria\trunk\VektoriaApp\Shaders\Cache\Object\Debug\OCC_PS.obj
//    /Fe
//    \\?\C:\Projects\Vektoria_2015-06-03\Vektoria\trunk\VektoriaApp\Shaders\Cache\Error\OCC_PS.txt
//    /Fc
//    \\?\C:\Projects\Vektoria_2015-06-03\Vektoria\trunk\VektoriaApp\Shaders\Cache\Assembly\50c07cb2.asm
//    \\?\C:\Projects\Vektoria_2015-06-03\Vektoria\trunk\VektoriaApp\shaders\Source\occulus.hlsl
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// Linear                            sampler      NA          NA    0        1
// tex2D[7]                          texture  float4          2d   19        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1     zw        1     NONE  float     zw
// TEXCOORD                 2   xy          2     NONE  float   xy  
// TEXCOORD                 3     z         2     NONE  float     z 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t19
dcl_input_ps linear v1.xy
dcl_input_ps linear v1.zw
dcl_input_ps linear v2.xy
dcl_input_ps linear v2.z
dcl_output o0.xyzw
dcl_temps 1

#line 39 "\\?\C:\Projects\Vektoria_2015-06-03\Vektoria\trunk\VektoriaApp\shaders\Source\occulus.hlsl"
sample_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t19.xyzw, s0
mov r0.x, r0.x  // R<0:Inf>
sample_indexable(texture2d)(float,float,float,float) r0.y, v1.zwzz, t19.xyzw, s0
mov r0.y, r0.y  // G<0:Inf>
sample_indexable(texture2d)(float,float,float,float) r0.z, v2.xyxx, t19.xyzw, s0
mov r0.z, r0.z  // B<0:Inf>
mov r0.w, l(1.000000)
mul o0.xyzw, r0.xyzw, v2.zzzz  // OCC_PS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3>
ret 
// Approximately 9 instruction slots used
