//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16 [unused]
//   float fA;                          // Offset:   16 Size:     4
//   float fH;                          // Offset:   20 Size:     4 [unused]
//   float fBumpStrength;               // Offset:   24 Size:     4 [unused]
//   float frTransparency;              // Offset:   28 Size:     4 [unused]
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16 [unused]
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16 [unused]
//   uint uImage;                       // Offset:   64 Size:     4 [unused]
//   uint uGlow;                        // Offset:   68 Size:     4 [unused]
//   uint uSpecular;                    // Offset:   72 Size:     4 [unused]
//   uint uBump;                        // Offset:   76 Size:     4 [unused]
//   uint uImageBlack;                  // Offset:   80 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:   84 Size:     4 [unused]
//   uint uSpecularAsImage;             // Offset:   88 Size:     4 [unused]
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4 [unused]
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4 [unused]
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4 [unused]
//   uint uChromaKeying;                // Offset:  120 Size:     4 [unused]
//   uint uEnvironment;                 // Offset:  124 Size:     4 [unused]
//   uint uPOM;                         // Offset:  128 Size:     4 [unused]
//   uint uTexBRDF;                     // Offset:  132 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  136 Size:     4 [unused]
//   uint uReflectionMap;               // Offset:  140 Size:     4 [unused]
//   uint uixPos;                       // Offset:  144 Size:     4 [unused]
//   uint uiyPos;                       // Offset:  148 Size:     4 [unused]
//   uint uixPics;                      // Offset:  152 Size:     4 [unused]
//   uint uiyPics;                      // Offset:  156 Size:     4 [unused]
//   float fRoughness;                  // Offset:  160 Size:     4 [unused]
//   float fIOR;                        // Offset:  164 Size:     4 [unused]
//   float fSpecular;                   // Offset:  168 Size:     4 [unused]
//   float fMetallic;                   // Offset:  172 Size:     4 [unused]
//   float fSubSurface;                 // Offset:  176 Size:     4 [unused]
//   float fAnistropic;                 // Offset:  180 Size:     4 [unused]
//   float fSheen;                      // Offset:  184 Size:     4 [unused]
//   float fSheenTint;                  // Offset:  188 Size:     4 [unused]
//   float fClearCoat;                  // Offset:  192 Size:     4 [unused]
//   float fClearCoatGloss;             // Offset:  196 Size:     4 [unused]
//   float fSpecularTint;               // Offset:  200 Size:     4 [unused]
//   uint uTextureAddressMode;          // Offset:  204 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// normalMap                         texture  float4          2d    0        1
// outputLEANMap                         UAV  float4     2darray    0        1
// TexInfo                           cbuffer      NA          NA    5        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb5[2], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_typed_texture2darray (float,float,float,float) u0
dcl_input vThreadGroupID.xy
dcl_input vThreadIDInGroup.xy
dcl_temps 4
dcl_thread_group 16, 16, 1

#line 18 "\\?\C:\Projects\Vektoria_2015-05-22_V13withPatch4\Vektoria\trunk\VektoriaApp\shaders\source\specularAA.hlsl"
imad r0.xy, vThreadGroupID.xyxx, l(16, 16, 0, 0), vThreadIDInGroup.xyxx  // u2SamplePos<0:[0u,1048575u],1:[0u,1048575u]>
nop 
mov r1.xy, r0.xyxx  // u2SamplePos<0:[0u,1048575u],1:[0u,1048575u]>

#line 9
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyzw, t0.xyzw
mul r1.xyz, r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000)
add r1.xyz, r1.xyzx, l(-1.000000, -1.000000, -1.000000, 0.000000)
div r1.xyz, r1.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
dp3 r1.w, r1.xyzx, r1.xyzx
rsq r1.w, r1.w
mul r1.xyz, r1.wwww, r1.xyzx  // f3Normal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mov r1.xyz, r1.xyzx  // FetchNormal<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 20
mov r1.xyz, r1.xyzx  // f3N<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
mul r1.w, l(3.321928), cb5[1].x
exp r1.w, r1.w
mul r1.z, r1.z, r1.w
div r1.xy, r1.xyxx, r1.zzzz  // f2B<0:NaN:Inf,1:NaN:Inf>
mul r2.x, r1.x, r1.x  // f3M<0:NaN:Inf>
mul r2.y, r1.y, r1.y  // f3M<1:NaN:Inf>
mul r2.z, r1.y, r1.x  // f3M<2:NaN:Inf>
mul r3.x, r1.x, r1.x
mul r3.y, r1.y, r1.y
add r2.w, r3.y, r3.x  // fCleanM<0:NaN:Inf>
mov r0.z, l(0)
mov r1.zw, l(0,0,0,1.000000)
store_uav_typed u0.xyzw, r0.xyzz, r1.xyzw  // outputLEANMap<0>
mov r0.w, l(1)
store_uav_typed u0.xyzw, r0.xyww, r2.xyzw  // outputLEANMap<0>

#line 15
ret 
// Approximately 29 instruction slots used
