//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E ShadowMapPS /Fo
//    \\?\C:\Projects\Vektoria_2016-06-20\Work\VektoriaApp\Shaders\Cache\Object\Release\ShadowMapPS.obj
//    /Fe
//    \\?\C:\Projects\Vektoria_2016-06-20\Work\VektoriaApp\Shaders\Cache\Error\ShadowMapPS.txt
//    /Fc
//    \\?\C:\Projects\Vektoria_2016-06-20\Work\VektoriaApp\Shaders\Cache\Assembly\73605c1f.asm
//    \\?\C:\Projects\Vektoria_2016-06-20\Work\VektoriaApp\Shaders\Source\shadowmap.hlsl
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
ps_5_0
dcl_globalFlags refactoringAllowed
ret 
// Approximately 1 instruction slots used
