//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /O1 /E ShadowMapVS /Fo
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Object\Release\ShadowMapVS.obj
//    /Fe
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Error\ShadowMapVS.txt
//    /Fc
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Assembly\84f719c6.asm
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Source\shadowmap.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer ObjectInfo
// {
//
//   float4x4 mWorld;                   // Offset:    0 Size:    64
//   float4x4 mLightView;               // Offset:   64 Size:    64
//   float4x4 mDummy;                   // Offset:  128 Size:    64 [unused]
//   float4x4 mProjection;              // Offset:  192 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// ObjectInfo                        cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
// NORMAL                   0   xyz         1     NONE  float       
// TEXCOORD                 0   xy          2     NONE  float       
// TANGENT                  0   xyz         3     NONE  float       
// BITANGENT                0   xyz         4     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Position              0   xyzw        0      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[16], immediateIndexed
dcl_input v0.xyzw
dcl_output_siv o0.xyzw, position
dcl_temps 2
dp4 r0.x, v0.xyzw, cb0[0].xyzw
dp4 r0.y, v0.xyzw, cb0[1].xyzw
dp4 r0.z, v0.xyzw, cb0[2].xyzw
dp4 r0.w, v0.xyzw, cb0[3].xyzw
dp4 r1.x, r0.xyzw, cb0[4].xyzw
dp4 r1.y, r0.xyzw, cb0[5].xyzw
dp4 r1.z, r0.xyzw, cb0[6].xyzw
dp4 r1.w, r0.xyzw, cb0[7].xyzw
dp4 o0.x, r1.xyzw, cb0[12].xyzw
dp4 o0.y, r1.xyzw, cb0[13].xyzw
dp4 o0.z, r1.xyzw, cb0[14].xyzw
dp4 o0.w, r1.xyzw, cb0[15].xyzw
ret 
// Approximately 13 instruction slots used
