//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float fBloomOriginalIntensity;     // Offset:    0 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:    4 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:    8 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   12 Size:     4 [unused]
//   float fRayExposure;                // Offset:   16 Size:     4 [unused]
//   float fRayDecay;                   // Offset:   20 Size:     4 [unused]
//   float fRayDensity;                 // Offset:   24 Size:     4 [unused]
//   float fRayWeight;                  // Offset:   28 Size:     4 [unused]
//   float fTimeDelta;                  // Offset:   32 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   36 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   40 Size:     4
//   float fDoFNear;                    // Offset:   44 Size:     4
//   float fRcpFrameX;                  // Offset:   48 Size:     4 [unused]
//   float fRcpFrameY;                  // Offset:   52 Size:     4 [unused]
//   uint uPad5;                        // Offset:   56 Size:     4 [unused]
//   uint uPad6;                        // Offset:   60 Size:     4 [unused]
//   float4 f4GodRayPos;                // Offset:   64 Size:    16 [unused]
//   float4 f4rcpFrameOpt;              // Offset:   80 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:   96 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// tex2D[7]                          texture  float4          2d   22        1
// tex2D[8]                          texture  float4          2d   23        1
// opaqueDepthTex                    texture   float          2d   24        1
// transparentDepthTex               texture   float          2d   26        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xy  
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[3], immediateIndexed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_resource_texture2d (float,float,float,float) t24
dcl_resource_texture2d (float,float,float,float) t26
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 4

#line 160 "\\?\C:\Projects\Vektoria_2015-05-22_V13withPatch4\Vektoria\trunk\VektoriaApp\shaders\source\BloomPost.hlsl"
nop 
ftoi r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.x, r0.xyzw, t24.xyzw
mov r0.x, r0.x  // fZBufferDepth<0:Inf>

#line 149
mov r0.y, -cb7[2].w
add r0.x, r0.y, r0.x
div r0.x, cb7[2].z, r0.x  // LinearDepth<0:NaN:Inf>

#line 160
mov r0.x, r0.x  // fOpaqueDepth<0:NaN:Inf>
nop 
ftoi r1.xy, v0.xyxx
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.z, r1.xyzw, t26.yzxw
mov r0.z, r0.z  // fZBufferDepth<0:Inf>

#line 149
add r0.y, r0.y, r0.z
div r0.y, cb7[2].z, r0.y  // LinearDepth<0:NaN:Inf>

#line 161
mov r0.y, r0.y  // fTransparentDepth<0:NaN:Inf>

#line 167
lt r0.z, r0.x, r0.y
movc r0.x, r0.z, r0.x, r0.y  // fDepth<0:NaN:Inf>
mul r0.x, r0.x, l(1.300000)
mov r0.x, -r0.x
add r0.x, r0.x, l(1.000000)  // fDepth<0:NaN:Inf>
mul r0.x, r0.x, l(1.300000)  // fBloomIntesity<0:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t23.xyzw, s1
mul r1.xyzw, r0.xxxx, r1.xyzw  // f4BloomColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, v1.xyxx, t22.xyzw, s1
mul r2.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)  // f4OriginalColor<0:Inf,1:Inf,2:Inf,3:Inf>

#line 178
nop 
mov r1.xyzw, r1.xyzw  // f4Color<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 122
dp3 r0.y, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
max r0.y, r0.y, l(0.000100)  // fGrey<0:Inf:[0.0001f,1.#INFf]>
mov r3.xyzw, -r0.yyyy
add r1.xyzw, r1.xyzw, r3.xyzw
mul r1.xyzw, r1.xyzw, l(1.300000, 1.300000, 1.300000, 1.300000)
add r1.xyzw, r0.yyyy, r1.xyzw  // AdjustSaturationB<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 178
mul r0.xyzw, r0.xxxx, r1.xyzw  // f4BloomColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
nop 
mov r2.xyzw, r2.xyzw  // f4Color<0:Inf,1:Inf,2:Inf,3:Inf>

#line 115
dp3 r1.x, r2.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
max r1.x, r1.x, l(0.000100)  // fGrey<0:Inf:[0.0001f,1.#INFf]>
mov r3.xyzw, -r1.xxxx
add r2.xyzw, r2.xyzw, r3.xyzw
mul r2.xyzw, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
add r1.xyzw, r1.xxxx, r2.xyzw  // AdjustSaturationO<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 179
mul r1.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)  // f4OriginalColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add o0.xyzw, r0.xyzw, r1.xyzw  // PS_BLOOMACCUM<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
ret 
// Approximately 47 instruction slots used
