//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer ObjectInfo
// {
//
//   float4x4 World;                    // Offset:    0 Size:    64
//
// }
//
// cbuffer TexInfo
// {
//
//   float fBloomOriginalIntensity;     // Offset:    0 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:    4 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:    8 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   12 Size:     4 [unused]
//   float fRayExposure;                // Offset:   16 Size:     4 [unused]
//   float fRayDecay;                   // Offset:   20 Size:     4 [unused]
//   float fRayDensity;                 // Offset:   24 Size:     4 [unused]
//   float fRayWeight;                  // Offset:   28 Size:     4 [unused]
//   float fTimeDelta;                  // Offset:   32 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   36 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   40 Size:     4 [unused]
//   float fDoFNear;                    // Offset:   44 Size:     4 [unused]
//   float fRcpFrameX;                  // Offset:   48 Size:     4 [unused]
//   float fRcpFrameY;                  // Offset:   52 Size:     4 [unused]
//   uint uPad5;                        // Offset:   56 Size:     4 [unused]
//   uint uPad6;                        // Offset:   60 Size:     4 [unused]
//   float4 f4GodRayPos;                // Offset:   64 Size:    16
//   float4 f4rcpFrameOpt;              // Offset:   80 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:   96 Size:    16 [unused]
//
// }
//
// cbuffer cbPerCamera
// {
//
//   float4x4 g_mViewProj;              // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// ObjectInfo                        cbuffer      NA          NA    0        1
// cbPerCamera                       cbuffer      NA          NA    1        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
// NORMAL                   0   xyz         1     NONE  float       
// TEXCOORD                 0   xy          2     NONE  float   xy  
// TANGENT                  0   xyz         3     NONE  float       
// BITANGENT                0   xyz         4     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xyzw
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1   xyzw        2     NONE  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[4], immediateIndexed
dcl_constantbuffer cb7[5], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_output o2.xyzw
dcl_temps 4

#line 45 "\\?\C:\Projects\Vektoria_2015-05-22_V13withPatch4\Vektoria\trunk\VektoriaApp\shaders\source\godrays.hlsl"
mov r0.xy, v2.xyxx  // output<4,5>
dp4 r1.x, v0.xyzw, cb0[0].xyzw  // output<0:NaN:Inf>
dp4 r1.y, v0.xyzw, cb0[1].xyzw  // output<1:NaN:Inf>
dp4 r1.z, v0.xyzw, cb0[2].xyzw  // output<2:NaN:Inf>
dp4 r1.w, v0.xyzw, cb0[3].xyzw  // output<3:NaN:Inf>
mul r2.xyz, l(1.000000, -1.000000, 1.000000, 0.000000), cb7[4].xyzx
mov r2.w, l(1.000000)
dp4 r3.x, r2.xyzw, cb0[0].xyzw  // f4LightPosIn<0:NaN:Inf>
dp4 r3.y, r2.xyzw, cb0[1].xyzw  // f4LightPosIn<1:NaN:Inf>
dp4 r3.z, r2.xyzw, cb0[2].xyzw  // f4LightPosIn<2:NaN:Inf>
dp4 r3.w, r2.xyzw, cb0[3].xyzw  // f4LightPosIn<3:NaN:Inf>
dp4 r2.x, r3.xyzw, cb1[0].xyzw  // output<6:NaN:Inf>
dp4 r2.y, r3.xyzw, cb1[1].xyzw  // output<7:NaN:Inf>
dp4 r2.z, r3.xyzw, cb1[2].xyzw  // output<8:NaN:Inf>
dp4 r2.w, r3.xyzw, cb1[3].xyzw  // output<9:NaN:Inf>
mov o0.xyzw, r1.xyzw  // VS_GODRAYS<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov o2.xyzw, r2.xyzw  // VS_GODRAYS<6:NaN:Inf,7:NaN:Inf,8:NaN:Inf,9:NaN:Inf>
mov o1.xy, r0.xyxx  // VS_GODRAYS<4,5>
ret 
// Approximately 19 instruction slots used
