//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E PS /Fo
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Object\Release\PS.obj
//    /Fe
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Error\PS.txt
//    /Fc
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Cache\Assembly\dec5d4d3.asm
//    \\?\C:\Projects\VektoriaV14_Alpha\AppHalloKugel\VektoriaApp\Shaders\Source\shaders_Standard.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4x4 mColor;                   // Offset:    0 Size:    64
//   float4 f4ColorAmbient;             // Offset:   64 Size:    16
//   float fSpecularSharpness;          // Offset:   80 Size:     4
//   float fDiffuseSharpness;           // Offset:   84 Size:     4 [unused]
//   float fBumpStrength;               // Offset:   88 Size:     4
//   float frTransparency;              // Offset:   92 Size:     4
//   float fHeightStrength;             // Offset:   96 Size:     4
//   float fFresnel;                    // Offset:  100 Size:     4
//   float fRefractionRatio;            // Offset:  104 Size:     4
//   float frTransparencyEdge;          // Offset:  108 Size:     4 [unused]
//   float4 f4ColorSSS;                 // Offset:  112 Size:    16
//   float4 f4SSSBRDFParams;            // Offset:  128 Size:    16
//   uint uImage;                       // Offset:  144 Size:     4
//   uint uGlow;                        // Offset:  148 Size:     4
//   uint uSpecular;                    // Offset:  152 Size:     4
//   uint uBump;                        // Offset:  156 Size:     4
//   uint uImageBlack;                  // Offset:  160 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:  164 Size:     4
//   uint uSpecularAsImage;             // Offset:  168 Size:     4
//   uint uHeightAsImage;               // Offset:  172 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:  176 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  180 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  184 Size:     4
//   uint uHeight;                      // Offset:  188 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  192 Size:     4
//   uint uGlowAsAmbient;               // Offset:  196 Size:     4
//   uint uChromaKeying;                // Offset:  200 Size:     4
//   uint uEnvironment;                 // Offset:  204 Size:     4
//   uint uPOM;                         // Offset:  208 Size:     4
//   uint uTexBRDF;                     // Offset:  212 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  216 Size:     4
//   uint uReflectionMap;               // Offset:  220 Size:     4 [unused]
//   uint uixPos;                       // Offset:  224 Size:     4
//   uint uiyPos;                       // Offset:  228 Size:     4
//   uint uixPics;                      // Offset:  232 Size:     4
//   uint uiyPics;                      // Offset:  236 Size:     4
//
// }
//
// cbuffer ViewportArt
// {
//
//   float4 f4SceneColorAmbient;        // Offset:    0 Size:    16
//   float4 f4FogParams;                // Offset:   16 Size:    16
//   float4x4 mColorModification;       // Offset:   32 Size:    64
//   uint uStyleColor;                  // Offset:   96 Size:     4
//   uint uStyleHalfTransparent;        // Offset:  100 Size:     4 [unused]
//   uint uStylePopart;                 // Offset:  104 Size:     4 [unused]
//   uint uStyleOutlining;              // Offset:  108 Size:     4 [unused]
//   uint uStyleMonochrome;             // Offset:  112 Size:     4 [unused]
//   uint uStyleOwn;                    // Offset:  116 Size:     4 [unused]
//   uint uStyleFog;                    // Offset:  120 Size:     4
//   uint uPad0;                        // Offset:  124 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    0        1
// shadowSampler                   sampler_c      NA          NA    2        1
// shadowMap                         texture  float4          2d   11        1
// tex2D[0]                          texture  float4          2d   15        1
// tex2D[1]                          texture  float4          2d   16        1
// tex2D[2]                          texture  float4          2d   17        1
// tex2D[3]                          texture  float4          2d   18        1
// tex2D[4]                          texture  float4          2d   19        1
// tex2D[5]                          texture  float4          2d   20        1
// tex2D[6]                          texture  float4          2d   21        1
// TexInfo                           cbuffer      NA          NA    1        1
// ViewportArt                       cbuffer      NA          NA    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// NORMAL                   0   xyz         1     NONE  float   xyz 
// LIGHTS                   5      w        1     NONE  float      w
// TANGENT                  0   xyz         2     NONE  float   xyz 
// LIGHTS                  16      w        2     NONE  float      w
// BITANGENT                0   xyz         3     NONE  float   xyz 
// LIGHTS                  17      w        3     NONE  float      w
// TEXCOORD                 0   xy          4     NONE  float   xy  
// LIGHTS                   4     zw        4     NONE  float     zw
// TEXCOORD                 1   xyz         5     NONE  float   xyz 
// LIGHTS                  29      w        5     NONE  float      w
// TEXCOORD                 2   xyzw        6     NONE  float   xyz 
// LIGHTS                   0   xyzw        7     NONE  float   xyzw
// LIGHTS                   2   xyzw        8     NONE  float   xyz 
// LIGHTS                   3   xyzw        9     NONE  float   xyzw
// LIGHTS                   6   xyzw       10     NONE   uint   xy  
// LIGHTS                  10   xyzw       11     NONE   uint   xyz 
// LIGHTS                  11   xyzw       12     NONE  float   xyzw
// LIGHTS                  12   xyzw       13     NONE  float   xyzw
// LIGHTS                  14   xyzw       14     NONE  float   xyz 
// LIGHTS                  15   xyzw       15     NONE  float   xyzw
// LIGHTS                  21   xyzw       16     NONE   uint    yzw
// LIGHTS                  23   xyzw       17     NONE  float   xyzw
// LIGHTS                  24   xyzw       18     NONE  float   xyzw
// LIGHTS                  26   xyzw       19     NONE  float   xyz 
// LIGHTS                  27   xyz        20     NONE  float   xyz 
// LIGHTS                  32   xyzw       21     NONE   uint     zw
// LIGHTS                  35   xyzw       22     NONE  float   xyzw
// LIGHTS                  36   xyzw       23     NONE  float   xyzw
// LIGHTS                  38   xyzw       24     NONE  float   xyz 
// LIGHTS                  39   xyz        25     NONE  float   xyz 
// LIGHTS                  43   xyzw       26     NONE   uint   x  w
// LIGHTS                  47   xyzw       27     NONE  float   xyzw
// COUNT                    0   x          28     NONE   uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb1[15], immediateIndexed
dcl_constantbuffer cb2[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s2, mode_comparison
dcl_resource_texture2d (float,float,float,float) t11
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t16
dcl_resource_texture2d (float,float,float,float) t17
dcl_resource_texture2d (float,float,float,float) t18
dcl_resource_texture2d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_input_ps linear v1.xyz
dcl_input_ps linear v1.w
dcl_input_ps linear v2.xyz
dcl_input_ps linear v2.w
dcl_input_ps linear v3.xyz
dcl_input_ps linear v3.w
dcl_input_ps linear v4.xy
dcl_input_ps linear v4.zw
dcl_input_ps linear v5.xyz
dcl_input_ps linear v5.w
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.xyzw
dcl_input_ps linear v8.xyz
dcl_input_ps linear v9.xyzw
dcl_input_ps constant v10.xy
dcl_input_ps constant v11.xyz
dcl_input_ps linear v12.xyzw
dcl_input_ps linear v13.xyzw
dcl_input_ps linear v14.xyz
dcl_input_ps linear v15.xyzw
dcl_input_ps constant v16.yzw
dcl_input_ps linear v17.xyzw
dcl_input_ps linear v18.xyzw
dcl_input_ps linear v19.xyz
dcl_input_ps linear v20.xyz
dcl_input_ps constant v21.zw
dcl_input_ps linear v22.xyzw
dcl_input_ps linear v23.xyzw
dcl_input_ps linear v24.xyz
dcl_input_ps linear v25.xyz
dcl_input_ps constant v26.xw
dcl_input_ps linear v27.xyzw
dcl_input_ps constant v28.x
dcl_output o0.xyzw
dcl_temps 17
add r0.xyz, -v5.xyzx, v6.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r0.xyzx
ult r2.xy, l(1, 1, 0, 0), cb1[14].zwzz
or r1.w, r2.y, r2.x
utof r2.xyzw, cb1[14].xyzw
div r2.xy, r2.xyxx, r2.zwzz
div r2.zw, l(1.000000, 1.000000, 1.000000, 1.000000), r2.zzzw
mad r2.xy, v4.xyxx, r2.zwzz, r2.xyxx
movc r2.xy, r1.wwww, r2.xyxx, v4.xyxx
ieq r1.w, cb1[13].x, l(1)
if_nz r1.w
  mul r3.xyz, v1.zxyz, v2.yzxy
  mad r3.xyz, v1.yzxy, v2.zxyz, -r3.xyzx
  dp3 r4.x, r1.xyzx, v2.xyzx
  dp3 r4.y, r1.xyzx, -r3.xyzx
  dp3 r1.w, r1.xyzx, v1.xyzx
  mul r2.zw, -r4.xxxy, cb1[6].xxxx
  mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 0.020000, 0.020000)
  div r2.zw, r2.zzzw, r1.wwww
  mad r1.w, r1.w, l(-15.000000), l(20.000000)
  ftoi r3.x, r1.w
  round_z r1.w, r1.w
  div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r1.w
  mul r3.yz, r1.wwww, r2.zzwz
  deriv_rtx_coarse r4.xy, r2.xyxx
  deriv_rty_coarse r4.zw, r2.xxxy
  add r3.w, -r1.w, l(1.000000)
  iadd r5.x, r3.x, l(1)
  mov r6.xyzw, l(0,0,0,0)
  mov r7.xy, l(0,0,0,0)
  mov r8.y, r3.w
  mov r8.xzw, l(0,0,1.000000,0)
  loop 
    ilt r7.z, r3.x, r8.x
    breakc_nz r7.z
    add r7.zw, r2.xxxy, r6.xxxy
    sample_d_indexable(texture2d)(float,float,float,float) r7.z, r7.zwzz, t20.yzxw, s0, r4.xyxx, r4.zwzz
    add r7.z, r7.z, r8.w
    mul r9.w, r7.z, l(0.500000)
    lt r7.w, r8.y, r9.w
    add r10.x, -r8.z, r8.w
    mad r7.z, -r7.z, l(0.500000), r8.w
    add r7.z, r8.y, r7.z
    add r7.z, -r8.z, r7.z
    div r7.z, r10.x, r7.z
    mad r10.xy, r7.zzzz, r3.yzyy, r6.zwzz
    iadd r9.x, r8.x, l(1)
    mad r10.zw, r2.zzzw, r1.wwww, r6.xxxy
    add r9.y, -r1.w, r8.y
    movc r10.zw, r7.wwww, r6.xxxy, r10.zzzw
    movc r6.zw, r7.wwww, r6.zzzw, r6.xxxy
    movc r7.xy, r7.wwww, r10.xyxx, r7.xyxx
    mov r5.yzw, r8.yyzw
    mov r9.z, r5.y
    movc r8.xyzw, r7.wwww, r5.xyzw, r9.xyzw
    mov r6.xy, r10.zwzz
  endloop 
  add r2.xy, r2.xyxx, r7.xyxx
endif 
if_nz cb1[9].w
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r2.xyxx, t18.xyzw, s0
  mad r3.xyz, r3.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  mul r2.zw, r3.xxxy, cb1[5].zzzz
  mul r3.xyw, r2.wwww, v3.xyxz
  mad r3.xyw, r2.zzzz, v2.xyxz, r3.xyxw
  mad r3.xyz, r3.zzzz, v1.xyzx, r3.xywx
  dp3 r1.w, r3.xyzx, r3.xyzx
  rsq r1.w, r1.w
  mul r3.xyz, r1.wwww, r3.xyzx
else 
  mov r3.xyz, v1.xyzx
endif 
umax r1.w, v28.x, l(1)
ult r4.xyz, l(1, 2, 3, 0), r1.wwww
if_nz r1.w
  dp3_sat r2.z, -v7.yzwy, r3.xyzx
  ieq r2.w, v11.x, l(3)
  if_nz r2.w
    dp3 r2.w, v7.yzwy, v9.xyzx
    lt r3.w, v1.w, r2.w
    if_nz r3.w
      lt r3.w, r2.w, v4.z
      add r2.w, r2.w, -v1.w
      add r4.w, -v1.w, v4.z
      div r2.w, r2.w, r4.w
      movc r2.w, r3.w, r2.w, l(1.000000)
      if_nz v10.x
        div r5.xyz, v12.xyzx, v12.wwww
        mad r6.xy, r5.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
        if_nz v10.y
          resinfo_indexable(texture2d)(float,float,float,float) r5.xy, l(0), t11.xyzw
          div r5.xy, l(1.316130, 1.316130, 0.000000, 0.000000), r5.xyxx
          mad r7.xy, r5.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), r6.xyxx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r7.xyxx, t11.xxxx, s2, r5.z
          mad r7.zw, r5.yyyx, l(0.000000, 0.000000, 2.000000, 2.000000), r6.yyyx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xzxx, t11.xxxx, s2, r5.z
          mul r4.w, r4.w, l(0.003663)
          mad r3.w, r3.w, l(0.003663), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.wyww, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.003663), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.wzww, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.003663), r3.w
          mov r6.zw, r7.xxxw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.zyzz, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.025641), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.wyww, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.025641), r3.w
          mov r7.x, r6.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.025641), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xzxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.025641), r3.w
          add r8.xy, -r5.xyxx, r6.xyxx
          mov r8.z, r6.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xzxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.095238), r3.w
          add r9.xy, r5.xyxx, r6.xyxx
          mov r9.z, r8.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.xzxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.095238), r3.w
          mov r7.w, r8.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xwxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.095238), r3.w
          mov r9.w, r7.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.wyww, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.095238), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.058608), r3.w
          mov r10.z, r9.x
          mov r10.x, r7.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.zxzz, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.058608), r3.w
          mov r8.w, r9.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xwxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.058608), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.058608), r3.w
          mov r10.yw, r6.zzzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.yxyy, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.wxww, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          mov r9.xz, r10.yywy
          mov r9.y, r8.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r9.zyzz, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          mov r10.x, r8.x
          mov r10.yw, r7.yyyz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.zyzz, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.xwxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r10.zwzz, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.014652), r3.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r6.xyxx, t11.xxxx, s2, r5.z
          mad r3.w, r4.w, l(0.150183), r3.w
        else 
          sample_c_lz_indexable(texture2d)(float,float,float,float) r3.w, r6.xyxx, t11.xxxx, s2, r5.z
        endif 
      else 
        mov r3.w, l(0)
      endif 
    else 
      mov r3.w, l(0)
      mov r2.w, l(0)
    endif 
  else 
    mov r3.w, l(1.000000)
    mov r2.w, l(1.000000)
  endif 
  mul r4.w, r2.z, v7.x
  mul r5.xyz, r4.wwww, v8.xyzx
  mul r5.xyz, r3.wwww, r5.xyzx
  mul r5.xyz, r2.wwww, r5.xyzx
else 
  mov r5.xyz, l(0,0,0,0)
  mov r2.z, l(0)
endif 
if_nz r4.x
  dp3_sat r2.w, -v13.yzwy, r3.xyzx
  add r2.z, r2.w, r2.z
  ieq r3.w, v16.y, l(3)
  if_nz r3.w
    dp3 r3.w, v13.yzwy, v15.xyzx
    lt r4.w, v3.w, r3.w
    if_nz r4.w
      lt r4.w, r3.w, v2.w
      add r3.w, r3.w, -v3.w
      add r5.w, v2.w, -v3.w
      div r3.w, r3.w, r5.w
      movc r3.w, r4.w, r3.w, l(1.000000)
      if_nz v11.y
        div r6.xyz, v17.xyzx, v17.wwww
        mad r7.xy, r6.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
        if_nz v11.z
          resinfo_indexable(texture2d)(float,float,float,float) r6.xy, l(0), t11.xyzw
          div r6.xy, l(1.316130, 1.316130, 0.000000, 0.000000), r6.xyxx
          mad r8.xy, r6.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), r7.xyxx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r8.zw, r6.yyyx, l(0.000000, 0.000000, 2.000000, 2.000000), r7.yyyx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mul r5.w, r5.w, l(0.003663)
          mad r4.w, r4.w, l(0.003663), r5.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wzww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          mov r7.zw, r8.xxxw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          mov r8.x, r7.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          add r9.xy, -r6.xyxx, r7.xyxx
          mov r9.z, r7.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          add r10.xy, r6.xyxx, r7.xyxx
          mov r10.z, r9.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r8.w, r9.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r10.w, r8.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.z, r10.x
          mov r11.x, r8.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zxzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r9.w, r10.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.yw, r7.zzzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.yxyy, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.wxww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r10.xz, r11.yywy
          mov r10.y, r9.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r11.x, r9.x
          mov r11.yw, r8.yyyz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zwzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.150183), r4.w
        else 
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t11.xxxx, s2, r6.z
        endif 
      else 
        mov r4.w, l(0)
      endif 
    else 
      mov r4.w, l(0)
      mov r3.w, l(0)
    endif 
  else 
    mov r4.w, l(1.000000)
    mov r3.w, l(1.000000)
  endif 
  mul r2.w, r2.w, v13.x
  mul r6.xyz, r2.wwww, v14.xyzx
  mul r6.xyz, r4.wwww, r6.xyzx
  mad r5.xyz, r6.xyzx, r3.wwww, r5.xyzx
endif 
if_nz r4.y
  dp3_sat r2.w, -v18.yzwy, r3.xyzx
  add r2.z, r2.w, r2.z
  ieq r3.w, v21.z, l(3)
  if_nz r3.w
    dp3 r3.w, v18.yzwy, v20.xyzx
    lt r4.w, v5.w, r3.w
    if_nz r4.w
      lt r4.w, r3.w, v4.w
      add r3.w, r3.w, -v5.w
      add r5.w, v4.w, -v5.w
      div r3.w, r3.w, r5.w
      movc r3.w, r4.w, r3.w, l(1.000000)
      if_nz v16.z
        div r6.xyz, v22.xyzx, v22.wwww
        mad r7.xy, r6.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
        if_nz v16.w
          resinfo_indexable(texture2d)(float,float,float,float) r6.xy, l(0), t11.xyzw
          div r6.xy, l(1.316130, 1.316130, 0.000000, 0.000000), r6.xyxx
          mad r8.xy, r6.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), r7.xyxx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r8.zw, r6.yyyx, l(0.000000, 0.000000, 2.000000, 2.000000), r7.yyyx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mul r5.w, r5.w, l(0.003663)
          mad r4.w, r4.w, l(0.003663), r5.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wzww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          mov r7.zw, r8.xxxw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          mov r8.x, r7.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          add r9.xy, -r6.xyxx, r7.xyxx
          mov r9.z, r7.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          add r10.xy, r6.xyxx, r7.xyxx
          mov r10.z, r9.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r8.w, r9.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r10.w, r8.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.z, r10.x
          mov r11.x, r8.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zxzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r9.w, r10.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.yw, r7.zzzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.yxyy, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.wxww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r10.xz, r11.yywy
          mov r10.y, r9.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r11.x, r9.x
          mov r11.yw, r8.yyyz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zwzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.150183), r4.w
        else 
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t11.xxxx, s2, r6.z
        endif 
      else 
        mov r4.w, l(0)
      endif 
    else 
      mov r4.w, l(0)
      mov r3.w, l(0)
    endif 
  else 
    mov r4.w, l(1.000000)
    mov r3.w, l(1.000000)
  endif 
  mul r2.w, r2.w, v18.x
  mul r6.xyz, r2.wwww, v19.xyzx
  mul r6.xyz, r4.wwww, r6.xyzx
  mad r5.xyz, r6.xyzx, r3.wwww, r5.xyzx
endif 
if_nz r4.z
  dp3_sat r2.w, -v23.yzwy, r3.xyzx
  add r2.z, r2.w, r2.z
  ieq r3.w, v26.w, l(3)
  if_nz r3.w
    dp3 r3.w, v23.yzwy, v25.xyzx
    lt r4.w, v15.w, r3.w
    if_nz r4.w
      lt r4.w, r3.w, v9.w
      add r3.w, r3.w, -v15.w
      add r5.w, v9.w, -v15.w
      div r3.w, r3.w, r5.w
      movc r3.w, r4.w, r3.w, l(1.000000)
      if_nz v21.w
        div r6.xyz, v27.xyzx, v27.wwww
        mad r7.xy, r6.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
        if_nz v26.x
          resinfo_indexable(texture2d)(float,float,float,float) r6.xy, l(0), t11.xyzw
          div r6.xy, l(1.316130, 1.316130, 0.000000, 0.000000), r6.xyxx
          mad r8.xy, r6.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), r7.xyxx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r8.zw, r6.yyyx, l(0.000000, 0.000000, 2.000000, 2.000000), r7.yyyx
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mul r5.w, r5.w, l(0.003663)
          mad r4.w, r4.w, l(0.003663), r5.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.wzww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.003663), r4.w
          mov r7.zw, r8.xxxw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          mov r8.x, r7.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.025641), r4.w
          add r9.xy, -r6.xyxx, r7.xyxx
          mov r9.z, r7.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          add r10.xy, r6.xyxx, r7.xyxx
          mov r10.z, r9.z
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xzxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r8.w, r9.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r8.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          mov r10.w, r8.x
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.wyww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.095238), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.z, r10.x
          mov r11.x, r8.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zxzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r9.w, r10.y
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r9.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.058608), r4.w
          mov r11.yw, r7.zzzw
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.yxyy, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.wxww, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r10.xz, r11.yywy
          mov r10.y, r9.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r10.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          mov r11.x, r9.x
          mov r11.yw, r8.yyyz
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zyzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.xwxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r11.zwzz, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.014652), r4.w
          sample_c_lz_indexable(texture2d)(float,float,float,float) r5.w, r7.xyxx, t11.xxxx, s2, r6.z
          mad r4.w, r5.w, l(0.150183), r4.w
        else 
          sample_c_lz_indexable(texture2d)(float,float,float,float) r4.w, r7.xyxx, t11.xxxx, s2, r6.z
        endif 
      else 
        mov r4.w, l(0)
      endif 
    else 
      mov r4.w, l(0)
      mov r3.w, l(0)
    endif 
  else 
    mov r4.w, l(1.000000)
    mov r3.w, l(1.000000)
  endif 
  mul r2.w, r2.w, v23.x
  mul r6.xyz, r2.wwww, v24.xyzx
  mul r6.xyz, r4.wwww, r6.xyzx
  mad r5.xyz, r6.xyzx, r3.wwww, r5.xyzx
endif 
if_nz cb1[9].z
  sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r2.xyxx, t15.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r7.xyzw, r2.xyxx, t17.zxyw, s0
  if_nz r1.w
    mad r8.xyz, r0.xyzx, r0.wwww, v7.yzwy
    dp3 r2.w, r8.xyzx, r8.xyzx
    rsq r2.w, r2.w
    mul r8.xyz, r2.wwww, r8.xyzx
    dp3 r2.w, r3.xyzx, r3.xyzx
    rsq r2.w, r2.w
    mul r9.xyz, r2.wwww, r3.xyzx
    dp3_sat r2.w, r9.xyzx, -r8.xyzx
    log r2.w, r2.w
    mul r2.w, r2.w, cb1[5].x
    exp r2.w, r2.w
    if_nz cb1[11].z
      mov r3.w, l(1.000000)
      mov r4.w, l(1.000000)
      mov r5.w, l(1.000000)
      mov r8.x, l(1.000000)
    else 
      if_nz cb1[10].z
        mov r3.w, r6.x
        mov r4.w, r6.y
        mov r5.w, r6.z
        mov r8.x, r6.w
      else 
        mov r3.w, r7.y
        mov r4.w, r7.z
        mov r5.w, r7.x
        mov r8.x, r7.w
      endif 
    endif 
    mul r8.yzw, r5.wwww, v8.xxyz
    add r8.yzw, r8.yyzw, r8.yyzw
    mul r9.xyz, r5.xyzx, r2.wwww
    mul r8.yzw, r8.yyzw, r9.xxyz
  else 
    mov r8.yzw, l(0,0,0,0)
  endif 
  if_nz r4.x
    mad r9.xyz, r0.xyzx, r0.wwww, v13.yzwy
    dp3 r2.w, r9.xyzx, r9.xyzx
    rsq r2.w, r2.w
    mul r9.xyz, r2.wwww, r9.xyzx
    dp3 r2.w, r3.xyzx, r3.xyzx
    rsq r2.w, r2.w
    mul r10.xyz, r2.wwww, r3.xyzx
    dp3_sat r2.w, r10.xyzx, -r9.xyzx
    log r2.w, r2.w
    mul r2.w, r2.w, cb1[5].x
    exp r2.w, r2.w
    if_nz cb1[11].z
      mov r3.w, l(1.000000)
      mov r4.xw, l(1.000000,0,0,1.000000)
      mov r8.x, l(1.000000)
    else 
      if_nz cb1[10].z
        mov r3.w, r6.x
        mov r4.xw, r6.zzzy
        mov r8.x, r6.w
      else 
        mov r3.w, r7.y
        mov r4.xw, r7.xxxz
        mov r8.x, r7.w
      endif 
    endif 
    mul r9.xyz, r4.xxxx, v14.xyzx
    add r9.xyz, r9.xyzx, r9.xyzx
    mul r10.xyz, r5.xyzx, r2.wwww
    mad r8.yzw, r9.xxyz, r10.xxyz, r8.yyzw
  endif 
  if_nz r4.y
    mad r9.xyz, r0.xyzx, r0.wwww, v18.yzwy
    dp3 r2.w, r9.xyzx, r9.xyzx
    rsq r2.w, r2.w
    mul r9.xyz, r2.wwww, r9.xyzx
    dp3 r2.w, r3.xyzx, r3.xyzx
    rsq r2.w, r2.w
    mul r10.xyz, r2.wwww, r3.xyzx
    dp3_sat r2.w, r10.xyzx, -r9.xyzx
    log r2.w, r2.w
    mul r2.w, r2.w, cb1[5].x
    exp r2.w, r2.w
    if_nz cb1[11].z
      mov r3.w, l(1.000000)
      mov r4.xw, l(1.000000,0,0,1.000000)
      mov r8.x, l(1.000000)
    else 
      if_nz cb1[10].z
        mov r3.w, r6.x
        mov r4.xw, r6.zzzy
        mov r8.x, r6.w
      else 
        mov r3.w, r7.y
        mov r4.xw, r7.xxxz
        mov r8.x, r7.w
      endif 
    endif 
    mul r9.xyz, r4.xxxx, v19.xyzx
    add r9.xyz, r9.xyzx, r9.xyzx
    mul r10.xyz, r5.xyzx, r2.wwww
    mad r8.yzw, r9.xxyz, r10.xxyz, r8.yyzw
  endif 
  if_nz r4.z
    mad r0.xyz, r0.xyzx, r0.wwww, v23.yzwy
    dp3 r0.w, r0.xyzx, r0.xyzx
    rsq r0.w, r0.w
    mul r0.xyz, r0.wwww, r0.xyzx
    dp3 r0.w, r3.xyzx, r3.xyzx
    rsq r0.w, r0.w
    mul r4.xyz, r0.wwww, r3.xyzx
    dp3_sat r0.x, r4.xyzx, -r0.xyzx
    log r0.x, r0.x
    mul r0.x, r0.x, cb1[5].x
    exp r0.x, r0.x
    if_nz cb1[11].z
      mov r3.w, l(1.000000)
      mov r4.w, l(1.000000)
      mov r7.x, l(1.000000)
      mov r8.x, l(1.000000)
    else 
      if_nz cb1[10].z
        mov r3.w, r6.x
        mov r4.w, r6.y
        mov r7.x, r6.z
        mov r8.x, r6.w
      else 
        mov r3.w, r7.y
        mov r4.w, r7.z
        mov r8.x, r7.w
      endif 
    endif 
    mul r0.yzw, r7.xxxx, v24.xxyz
    add r0.yzw, r0.yyzw, r0.yyzw
    mul r4.xyz, r5.xyzx, r0.xxxx
    mad r8.yzw, r0.yyzw, r4.xxyz, r8.yyzw
  endif 
else 
  mov r3.w, l(0)
  mov r4.w, l(0)
  mov r8.xyzw, l(0,0,0,0)
endif 
add r0.x, -r2.z, l(1.000000)
if_nz cb1[9].y
  if_nz cb1[12].y
    mov r0.yzw, cb1[4].xxyz
  else 
    if_nz cb1[10].y
      sample_indexable(texture2d)(float,float,float,float) r0.yzw, r2.xyxx, t15.wxyz, s0
    else 
      sample_indexable(texture2d)(float,float,float,float) r0.yzw, r2.xyxx, t16.wxyz, s0
    endif 
  endif 
else 
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r2.xyxx, t15.xyzw, s0
  mul r0.yzw, r4.xxyz, cb2[0].xxyz
endif 
mul r6.xyz, r0.xxxx, r0.yzwy
mov r6.w, l(1.000000)
dp4 r4.x, r6.xyzw, cb1[0].xyzw
dp4 r4.y, r6.xyzw, cb1[1].xyzw
dp4 r4.z, r6.xyzw, cb1[2].xyzw
add r0.y, -r8.x, l(1.000000)
mul r6.xyz, r0.yyyy, r6.xyzx
mad r4.xyz, r4.xyzx, r8.xxxx, r6.xyzx
sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r2.xyxx, t15.xyzw, s0
dp4 r7.x, r6.xyzw, cb1[0].xyzw
dp4 r7.y, r6.xyzw, cb1[1].xyzw
dp4 r7.z, r6.xyzw, cb1[2].xyzw
dp4 r7.w, r6.xyzw, cb1[3].xyzw
mul r9.xyzw, r0.yyyy, r6.xyzw
mad r7.xyzw, r7.xyzw, r8.xxxx, r9.xyzw
if_nz cb1[12].z
  resinfo_indexable(texture2d)(float,float,float,float)_uint r0.yz, l(0), t15.zxyw
  ld_indexable(texture2d)(float,float,float,float) r9.xyz, l(0, 0, 0, 0), t15.xyzw
  utof r0.yz, r0.yyzy
  mul r0.yz, r0.yyzy, r2.xxyx
  ftoi r10.xy, r0.yzyy
  mov r10.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r10.xyzw, r10.xyzw, t15.xyzw
  eq r0.yzw, r10.xxyz, r9.xxyz
  and r0.y, r0.z, r0.y
  and r0.y, r0.w, r0.y
  mov r7.w, l(0)
  movc r7.xyzw, r0.yyyy, r7.xyzw, r10.xyzw
endif 
mul r0.xyz, r0.xxxx, r4.xyzx
mad r0.xyz, r5.xyzx, r7.xyzx, r0.xyzx
movc r0.xyz, cb1[12].xxxx, r0.xyzx, r7.xyzx
dp3 r0.w, -r1.xyzx, r3.xyzx
max r0.w, r0.w, l(0.000000)
add r0.w, -r0.w, l(1.000000)
mul r2.z, r0.w, r0.w
mul r2.w, r2.z, r2.z
mul r0.w, r0.w, r2.w
mul r2.w, r0.w, cb1[6].y
if_nz cb1[12].w
  add r4.x, -r4.w, l(1.000000)
  mad r4.y, r4.x, r2.w, r4.w
  min r4.y, r4.y, l(1.000000)
  mad r2.w, -r4.x, r2.w, r3.w
  max r2.w, r2.w, l(0.000000)
  add r3.w, -r2.w, l(1.000000)
  add r3.w, -r4.y, r3.w
  add r3.w, -r4.w, r3.w
  dp3 r4.x, r1.xyzx, r3.xyzx
  add r4.z, r4.x, r4.x
  mad r5.xyz, r3.yxzy, -r4.zzzz, r1.yxzy
  mul r4.z, cb1[6].z, cb1[6].z
  mad r5.w, -r4.x, r4.x, l(1.000000)
  mad r4.z, -r4.z, r5.w, l(1.000000)
  sqrt r5.w, r4.z
  mad r4.x, cb1[6].z, r4.x, r5.w
  ge r4.z, r4.z, l(0.000000)
  mul r7.xyz, r3.yxzy, r4.xxxx
  mad r7.xyz, cb1[6].zzzz, r1.yxzy, -r7.xyzx
  and r7.xyz, r4.zzzz, r7.xyzx
  ieq r4.x, cb1[12].w, l(2)
  if_nz r4.x
    ge r9.xyzw, |r7.xxyy|, |r7.yzxz|
    lt r10.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r7.xyzx
    div r11.xyzw, -r7.yzxz, |r7.zxyy|
    div r12.xyzw, r7.yyzz, |r7.zxxy|
    mov r13.x, r12.y
    mov r13.y, r11.y
    mov r13.zw, l(0,0,0.500000,0.250000)
    mov r14.xw, r13.xxxw
    mov r14.y, r12.z
    mov r14.z, l(0.833333)
    movc r13.xyzw, r10.xxxx, r13.xyzw, r14.xyzw
    and r4.xz, r9.yywy, r9.xxzx
    mov r9.x, r12.w
    mov r9.y, r11.z
    mov r9.zw, l(0,0,0.833333,0.750000)
    mov r14.xy, r11.wzww
    mov r14.zw, l(0,0,0.166667,0.750000)
    movc r9.xyzw, r10.yyyy, r9.xyzw, r14.xyzw
    div r11.y, -r7.x, |r7.z|
    mov r11.zw, l(0,0,0.166667,0.250000)
    mov r12.y, r11.y
    mov r12.zw, l(0,0,0.500000,0.750000)
    movc r10.xyzw, r10.zzzz, r11.xyzw, r12.xyzw
    movc r9.xyzw, r4.zzzz, r9.xyzw, r10.xyzw
    movc r9.xyzw, r4.xxxx, r13.xyzw, r9.xyzw
    max r10.x, |r9.y|, |r9.x|
    mad r4.xz, r9.xxyx, l(0.166666, 0.000000, 0.249999, 0.000000), r9.zzwz
    ge r9.xyzw, |r5.xxyy|, |r5.yzxz|
    lt r11.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xyzx
    div r12.xyzw, -r5.yzxz, |r5.zxyy|
    div r13.xyzw, r5.yyzz, |r5.zxxy|
    mov r14.x, r13.y
    mov r14.y, r12.y
    mov r14.zw, l(0,0,0.500000,0.250000)
    mov r15.xw, r14.xxxw
    mov r15.y, r13.z
    mov r15.z, l(0.833333)
    movc r14.xyzw, r11.xxxx, r14.xyzw, r15.xyzw
    and r9.xy, r9.ywyy, r9.xzxx
    mov r15.x, r13.w
    mov r15.y, r12.z
    mov r15.zw, l(0,0,0.833333,0.750000)
    mov r16.xy, r12.wzww
    mov r16.zw, l(0,0,0.166667,0.750000)
    movc r15.xyzw, r11.yyyy, r15.xyzw, r16.xyzw
    div r12.y, -r5.x, |r5.z|
    mov r12.zw, l(0,0,0.166667,0.250000)
    mov r13.y, r12.y
    mov r13.zw, l(0,0,0.500000,0.750000)
    movc r11.xyzw, r11.zzzz, r12.xyzw, r13.xyzw
    movc r11.xyzw, r9.yyyy, r15.xyzw, r11.xyzw
    movc r9.xyzw, r9.xxxx, r14.xyzw, r11.xyzw
    max r10.y, |r9.y|, |r9.x|
    mad r9.xy, r9.xyxx, l(0.166666, 0.249999, 0.000000, 0.000000), r9.zwzz
  else 
    div r5.w, r7.y, r7.z
    min r6.w, |r5.w|, l(1.000000)
    max r8.x, |r5.w|, l(1.000000)
    div r8.x, l(1.000000, 1.000000, 1.000000, 1.000000), r8.x
    mul r6.w, r6.w, r8.x
    mul r8.x, r6.w, r6.w
    mad r9.z, r8.x, l(0.020835), l(-0.085133)
    mad r9.z, r8.x, r9.z, l(0.180141)
    mad r9.z, r8.x, r9.z, l(-0.330299)
    mad r8.x, r8.x, r9.z, l(0.999866)
    mul r9.z, r6.w, r8.x
    lt r9.w, l(1.000000), |r5.w|
    mad r9.z, r9.z, l(-2.000000), l(1.570796)
    and r9.z, r9.w, r9.z
    mad r6.w, r6.w, r8.x, r9.z
    min r5.w, r5.w, l(1.000000)
    lt r5.w, r5.w, -r5.w
    movc r5.w, r5.w, -r6.w, r6.w
    ge r6.w, r7.y, l(0.000000)
    lt r7.y, r7.z, l(0.000000)
    add r9.zw, r5.wwww, l(0.000000, 0.000000, 3.141593, 6.283185)
    movc r5.w, r7.y, r9.z, r5.w
    movc r7.y, r7.y, r9.z, r9.w
    movc r5.w, r6.w, r5.w, r7.y
    mul r4.x, r5.w, l(0.159155)
    add r6.w, -|r7.x|, l(1.000000)
    sqrt r6.w, r6.w
    mad r7.y, |r7.x|, l(-0.018729), l(0.074261)
    mad r7.y, r7.y, |r7.x|, l(-0.212114)
    mad r7.y, r7.y, |r7.x|, l(1.570729)
    mul r7.z, r6.w, r7.y
    mad r7.z, r7.z, l(-2.000000), l(3.141593)
    lt r7.x, r7.x, -r7.x
    and r7.x, r7.x, r7.z
    mad r6.w, r7.y, r6.w, r7.x
    mul r4.z, r6.w, l(0.318310)
    lt r6.w, r5.w, l(0.062832)
    lt r5.w, l(6.220354), r5.w
    or r5.w, r6.w, r5.w
    and r10.x, r5.w, l(0x3f800000)
    div r5.w, r5.y, r5.z
    min r6.w, |r5.w|, l(1.000000)
    max r7.x, |r5.w|, l(1.000000)
    div r7.x, l(1.000000, 1.000000, 1.000000, 1.000000), r7.x
    mul r6.w, r6.w, r7.x
    mul r7.x, r6.w, r6.w
    mad r7.y, r7.x, l(0.020835), l(-0.085133)
    mad r7.y, r7.x, r7.y, l(0.180141)
    mad r7.y, r7.x, r7.y, l(-0.330299)
    mad r7.x, r7.x, r7.y, l(0.999866)
    mul r7.y, r6.w, r7.x
    lt r7.z, l(1.000000), |r5.w|
    mad r7.y, r7.y, l(-2.000000), l(1.570796)
    and r7.y, r7.z, r7.y
    mad r6.w, r6.w, r7.x, r7.y
    min r5.w, r5.w, l(1.000000)
    lt r5.w, r5.w, -r5.w
    movc r5.w, r5.w, -r6.w, r6.w
    ge r5.y, r5.y, l(0.000000)
    lt r5.z, r5.z, l(0.000000)
    add r7.xy, r5.wwww, l(3.141593, 6.283185, 0.000000, 0.000000)
    movc r5.w, r5.z, r7.x, r5.w
    movc r5.z, r5.z, r7.x, r7.y
    movc r5.y, r5.y, r5.w, r5.z
    add r5.z, -|r5.x|, l(1.000000)
    sqrt r5.z, r5.z
    mad r5.w, |r5.x|, l(-0.018729), l(0.074261)
    mad r5.w, r5.w, |r5.x|, l(-0.212114)
    mad r5.w, r5.w, |r5.x|, l(1.570729)
    mul r6.w, r5.z, r5.w
    mad r6.w, r6.w, l(-2.000000), l(3.141593)
    lt r5.x, r5.x, -r5.x
    and r5.x, r5.x, r6.w
    mad r5.x, r5.w, r5.z, r5.x
    mul r9.xy, r5.yxyy, l(0.159155, 0.318310, 0.000000, 0.000000)
    lt r5.x, r5.y, l(0.062832)
    lt r5.y, l(6.220354), r5.y
    or r5.x, r5.x, r5.y
    and r10.y, r5.x, l(0x3f800000)
  endif 
  resinfo_indexable(texture2d)(float,float,float,float)_uint r5.xy, l(0), t19.xyzw
  lt r5.zw, l(0.000000, 0.000000, 0.900000, 0.900000), r10.xxxy
  sample_indexable(texture2d)(float,float,float,float) r7.xyz, r4.xzxx, t19.xyzw, s0
  if_nz r5.z
    utof r9.zw, r5.xxxy
    mul r4.xz, r4.xxzx, r9.zzwz
    ftoi r10.xy, r4.xzxx
    mov r10.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r7.xyz, r10.xyzw, t19.xyzw
  endif 
  sample_indexable(texture2d)(float,float,float,float) r10.xyz, r9.xyxx, t19.xyzw, s0
  if_nz r5.w
    utof r4.xz, r5.xxyx
    mul r4.xz, r4.xxzx, r9.xxyx
    ftoi r5.xy, r4.xzxx
    mov r5.zw, l(0,0,0,0)
    ld_indexable(texture2d)(float,float,float,float) r10.xyz, r5.xyzw, t19.xyzw
  endif 
  mul r4.xyz, r4.yyyy, r10.xyzx
  mad r4.xyz, r7.xyzx, r2.wwww, r4.xyzx
  mad r4.xyz, r8.yzwy, r4.wwww, r4.xyzx
  mad r4.xyz, r0.xyzx, r3.wwww, r4.xyzx
else 
  mad r0.w, r0.w, cb1[6].y, l(1.000000)
  mad r4.xyz, r8.yzwy, r0.wwww, r0.xyzx
endif 
mov_sat r7.w, r7.w
add r0.x, l(1.000000), -cb1[5].w
mad r0.x, r7.w, r0.x, cb1[4].w
movc r4.w, cb1[9].x, r0.x, cb1[4].w
if_nz cb1[13].z
  sample_indexable(texture2d)(float,float,float,float) r0.xyz, r2.xyxx, t21.xyzw, s0
  dp3 r0.x, r0.xyzx, r0.xyzx
  sqrt r0.x, r0.x
  mov r5.w, l(1.000000)
  mov r7.xyzw, l(0,0,0,0)
  mov r0.y, l(0)
  loop 
    uge r0.w, r0.y, r1.w
    breakc_nz r0.w
    ult r2.xyw, r0.yyyy, l(1, 2, 0, 3)
    and r9.xyz, r2.xxxx, v7.yzwy
    ineg r0.w, r0.y
    and r0.w, r0.w, r2.y
    and r10.xyz, r0.wwww, v13.yzwy
    or r9.xyz, r9.xyzx, r10.xyzx
    iadd r0.yz, r0.yyyy, l(0, 1, -3, 0)
    movc r0.z, r2.y, l(0), r0.z
    and r10.xyz, r0.zzzz, v18.yzwy
    or r9.xyz, r9.xyzx, r10.xyzx
    ieq r2.y, r2.w, l(0)
    and r10.xyz, r2.yyyy, v23.yzwy
    or r9.xyz, r9.xyzx, r10.xyzx
    and r10.xyz, r2.xxxx, v8.xyzx
    and r11.xyz, r0.wwww, v14.xyzx
    or r10.xyz, r10.xyzx, r11.xyzx
    and r11.xyz, r0.zzzz, v19.xyzx
    or r10.xyz, r10.xyzx, r11.xyzx
    and r2.xyw, r2.yyyy, v24.xyxz
    or r2.xyw, r10.xyxz, r2.xyxw
    dp3 r0.z, r9.xyzx, r3.xyzx
    mad r0.w, r0.z, l(0.500000), l(0.500000)
    dp3 r3.w, -r3.xyzx, r9.xyzx
    max r3.w, r3.w, l(0.000000)
    dp3 r6.w, r1.xyzx, r9.xyzx
    mad r6.w, r6.w, l(0.500000), l(0.500000)
    mul r6.w, r6.w, cb1[8].x
    mad r3.w, cb1[8].x, r3.w, r6.w
    mul r10.xyz, r3.wwww, cb1[7].xyzx
    mul r10.xyz, r0.xxxx, r10.xyzx
    max r0.z, r0.z, l(0.000000)
    mul r11.xyz, r8.yzwy, r0.zzzz
    mul r11.xyz, r2.zzzz, r11.xyzx
    mad r10.xyz, r0.wwww, r6.xyzx, r10.xyzx
    mad r10.xyz, r11.xyzx, cb1[8].zzzz, r10.xyzx
    add r9.xyz, r3.xyzx, r9.xyzx
    dp3 r0.z, r9.xyzx, r9.xyzx
    rsq r0.z, r0.z
    mul r9.xyz, r0.zzzz, r9.xyzx
    dp3_sat r0.z, r3.xyzx, r9.xyzx
    mul r9.xyz, r8.yzwy, r0.zzzz
    mad r9.xyz, r9.xyzx, cb1[8].yyyy, r10.xyzx
    mul r5.xyz, r2.xywx, r9.xyzx
    mov r7.xyzw, r5.xyzw
  endloop 
  mul r4.xyzw, r4.xyzw, r7.xyzw
endif 
add r0.xyz, v5.xyzx, -v6.xyzx
dp3 r0.x, r0.xyzx, r0.xyzx
sqrt r0.x, r0.x
div r0.x, r0.x, cb2[1].w
add r0.xyz, r0.xxxx, r4.xyzx
movc r4.xyz, cb2[7].zzzz, r0.xyzx, r4.xyzx
dp4 r0.x, r4.xyzw, cb2[2].xyzw
dp4 r0.y, r4.xyzw, cb2[3].xyzw
dp4 r0.z, r4.xyzw, cb2[4].xyzw
dp4 r0.w, r4.xyzw, cb2[5].xyzw
movc o0.xyzw, cb2[6].xxxx, r0.xyzw, r4.xyzw
ret 
// Approximately 956 instruction slots used
