//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float fBloomOriginalIntensity;     // Offset:    0 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:    4 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:    8 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   12 Size:     4 [unused]
//   float fRayExposure;                // Offset:   16 Size:     4
//   float fRayDecay;                   // Offset:   20 Size:     4
//   float fRayDensity;                 // Offset:   24 Size:     4
//   float fRayWeight;                  // Offset:   28 Size:     4
//   float fTimeDelta;                  // Offset:   32 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   36 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   40 Size:     4 [unused]
//   float fDoFNear;                    // Offset:   44 Size:     4 [unused]
//   float fRcpFrameX;                  // Offset:   48 Size:     4
//   float fRcpFrameY;                  // Offset:   52 Size:     4
//   uint uPad5;                        // Offset:   56 Size:     4 [unused]
//   uint uPad6;                        // Offset:   60 Size:     4 [unused]
//   float4 f4GodRayPos;                // Offset:   64 Size:    16 [unused]
//   float4 f4rcpFrameOpt;              // Offset:   80 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:   96 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// pointSampler                      sampler      NA          NA    2        1
// tex2D[7]                          texture  float4          2d   22        1
// godRayTex                         texture  float4          2d   24        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1   xyzw        2     NONE  float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[4], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t24
dcl_input_ps linear v1.xy
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 6

#line 85 "\\?\C:\Projects\Vektoria_2015-05-22_V13withPatch4\Vektoria\trunk\VektoriaApp\shaders\source\godrays.hlsl"
mul r0.x, v2.x, cb7[3].x
add r0.x, r0.x, l(0.500000)  // f2LightPos<0:Inf>
mul r0.z, v2.y, cb7[3].y
add r0.y, r0.z, l(0.500000)  // f2LightPos<1:Inf>

#line 89
mov r0.xy, -r0.xyxx
add r0.xy, r0.xyxx, v1.xyxx  // f2DeltaTexCoord<0:Inf,1:Inf>
mov r0.zw, v1.xxxy  // f2texCoord<0,1>
mul r1.x, l(0.006667), cb7[1].z
mul r0.xy, r0.xyxx, r1.xxxx  // f2DeltaTexCoord<0:NaN:Inf,1:NaN:Inf>

#line 94
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t22.xyzw, s1  // f4SceneColor<0:Inf,1:Inf,2:Inf,3:Inf>
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, v1.xyxx, t24.xyzw, s2  // f4Depth<0:Inf,1:Inf,2:Inf,3:Inf>
mov r1.xyzw, r1.xyzw  // f4SceneColorCurr<0:Inf,1:Inf,2:Inf,3:Inf>

#line 101
mov r0.xy, -r0.xyxx
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.x, l(1.000000), cb7[1].w
mul r3.xyzw, r3.xyzw, r4.xxxx  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r1.xyzw, r3.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, l(1.000000), cb7[1].y  // fIllumDecay<0>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.zw, r0.xxxy, r0.zzzw  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r0.zwzz, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.y, r4.x, cb7[1].w
mul r5.xyzw, r4.yyyy, r5.xyzw  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r3.xyzw, r3.xyzw, r5.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r4.x, r4.x, cb7[1].y  // fIllumDecay<0:NaN:Inf>

#line 101
add r0.xy, r0.xyxx, r0.zwzz  // f2texCoord<0:NaN:Inf,1:NaN:Inf>
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyxx, t24.xyzw, s2  // f4Sample<0:Inf,1:Inf,2:Inf,3:Inf>
mul r4.x, r4.x, cb7[1].w
mul r0.xyzw, r0.xyzw, r4.xxxx  // f4Sample<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
add r0.xyzw, r0.xyzw, r3.xyzw  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>

#line 108
mul r0.xyzw, r0.xyzw, cb7[1].xxxx  // f4SceneColor<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mul r0.xyzw, r0.xyzw, r2.xyzw
add r0.xyzw, r0.xyzw, r1.xyzw  // f4SceneColorCurr<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
mov o0.xyzw, r0.xyzw  // PS_GODRAYS_ACCUM<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf,3:NaN:Inf>
ret 
// Approximately 917 instruction slots used
